version: "3.7"

services:
    app:
        build: ./app
        ports:
            - "80:5000"
        networks:
            - backend
        depends_on:
            - db
    init-db:
        build: ./init-db
        networks:
            - backend
        volumes:
            - type: bind
              source: ./init-db/raw
              target: /raw
              read_only: true
        environment:
            PYTHONUNBUFFERED: 1
        depends_on:
            - db
    db:
        image: postgres:10.5-alpine
        networks:
            - backend
        volumes:
            - db-data:/var/lib/postgresql/data
networks:
    backend:
volumes:
    db-data:
