version: "3.7"

services:
    web:
        build: ./web
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - app
    app:
        build: ./app
        ports:
            - "8080:8080"
        networks:
            frontend:
                aliases:
                    - app-frontend
            backend:
        depends_on:
            - db
    init-db:
        build: ./init-db
        networks:
            - backend
        volumes:
            - type: bind
              source: ./init-db/raw
              target: /raw
              read_only: true
        environment:
            PYTHONUNBUFFERED: 1
        depends_on:
            - db
    db:
        image: postgres:10.5-alpine
        networks:
            - backend
        volumes:
            - db-data:/var/lib/postgresql/data
networks:
    backend:
    frontend:
volumes:
    db-data:
